baseURL = "http://ui.funky.studio/"
languageCode = "en-us"
title = "Funky UI SCSS-JS Library"

pygmentsCodefences = true
pygmentsUseClasses = true

pluralizeListTitles = false
SectionPagesMenu = "main"
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
